---
http_interactions:
- request:
    method: get
    uri: https://app.wercker.com/api/v3/applications/StupidCodeFactory/wercker_api/builds
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
      Authorization:
      - Bearer some_api_token
  response:
    status:
      code: 200
      message: OK
    headers:
      Cache-Control:
      - private, no-cache, no-store, must-revalidate
      Content-Type:
      - application/json; charset=utf-8
      Date:
      - Mon, 03 Jul 2017 20:55:45 GMT
      Etag:
      - W/"2-d4cbb29"
      Server:
      - nginx
      Set-Cookie:
      - express.sid=s%3A9ia6oyTeI2kEFaKQkNnbd0zXn27FVy2E.zotTs7td0ca4acGbz6rrNA1ixUfSt6a%2FqWzPK2DZNAk;
        Path=/; Expires=Mon, 17 Jul 2017 20:55:45 GMT; HttpOnly; Secure
      Strict-Transport-Security:
      - max-age=10886400; includeSubDomains; preload
      X-Content-Type-Options:
      - nosniff
      X-Frame-Options:
      - DENY
      X-Powered-By:
      - Express
      Content-Length:
      - '2'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: "[]"
    http_version: 
  recorded_at: Mon, 03 Jul 2017 20:55:45 GMT
recorded_with: VCR 3.0.3
