---
http_interactions:
- request:
    method: get
    uri: https://app.wercker.com/api/v3/applications/StupidCodeFactory/wercker_api
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
      Authorization:
      - Bearer some_api_token
  response:
    status:
      code: 200
      message: OK
    headers:
      Cache-Control:
      - private, no-cache, no-store, must-revalidate
      Content-Type:
      - application/json; charset=utf-8
      Date:
      - Mon, 03 Jul 2017 20:29:42 GMT
      Etag:
      - W/"31fsfD1bE1EtL4NjbUWumg=="
      Server:
      - nginx
      Set-Cookie:
      - express.sid=s%3AdoFPQbYznzvvs67QzHJJcpeIh8pTFsv1.AMFmsWkppWuG0XkTGhkHXMYfLSXPK6or3vBzJaxsxbs;
        Path=/; Expires=Mon, 17 Jul 2017 20:29:42 GMT; HttpOnly; Secure
      Strict-Transport-Security:
      - max-age=10886400; includeSubDomains; preload
      X-Content-Type-Options:
      - nosniff
      X-Frame-Options:
      - DENY
      X-Powered-By:
      - Express
      Transfer-Encoding:
      - chunked
      Connection:
      - keep-alive
    body:
      encoding: ASCII-8BIT
      string: '{"id":"595a6b1ba01812010072fc1c","url":"https://app.wercker.com/api/v3/applications/stupidcodefactory/wercker_api","name":"wercker_api","owner":{"type":"wercker","name":"yann","avatar":{"gravatar":"a4346267407e112504b5dab1dac534ea"},"userId":"56a4de11212b43b24e0b6175","meta":{"username":"StupidCodeFactory","type":"user","werckerEmployee":false}},"builds":"https://app.wercker.com/api/v3/applications/stupidcodefactory/wercker_api/builds","deploys":"https://app.wercker.com/api/v3/applications/stupidcodefactory/wercker_api/deploys","scm":{"type":"git","owner":"StupidCodeFactory","domain":"github.com","repository":"wercker_api"},"badgeKey":"15fd697b0b3ff854e408a5c256e6737b","createdAt":"2017-07-03T16:04:43.374Z","updatedAt":"2017-07-03T20:29:33.041Z","allowedActions":["delete_project","update_project","transfer_ownership_project","update_checkout_key","migrate_application","list_authorizations","create_authorization","read_authorization","update_authorization","delete_authorization","read_heroku_collaborators","send_invites","create_key","delete_key","update_key","update_teams","delete_team","update_org","create_member","delete_member","update_member","create_team_members","delete_team_members","org_create_app","org_transferownership_app","org_transfer_apiUser_app","update_project_button","cancel_customer","create_customer","get_customer","update_customer","get_billing","update_billing","update_extended_permissions","get_invoice","list_invoices","list_orginvitations","create_orginvitation","get_orginvitation","delete_orginvitation","resend_orginvitation","deploy_build","reset_deploy_warnings","create_deploytarget","create_target","update_target","delete_target","create_target_trigger","update_target_trigger","read_target_trigger","delete_target_trigger","read_deploytarget","abort_deploy","update_deploytarget","delete_deploytarget","read_deploytargetsettings","application_envcollection","list_key","read_key","create_env_var","update_env_var","delete_env_var","build_project","rebuild_build","abort_build","read_deploy","list_deploysteps","read_deploystep","read_deploytarget_logs","add_pullrequest","receive_push","autodeploy_build","fix_webhook","clear_cache_project","list_teams","list_members","org_read_wallItem","read_docker_image","create_run","abort_run","list_extended_permissions","read_env_var","read_project","list_builds","read_build","list_runs","read_run","list_runsteps","read_runstep","list_buildsteps","read_buildstep","follow_project","unfollow_project","list_targets","read_target","list_workflows","list_collaborators","list_comment","create_comment"],"theme":"Amethyst","settings":{"privacy":"public","stack":6,"ignoredBranches":[]}}'
    http_version: 
  recorded_at: Mon, 03 Jul 2017 20:29:42 GMT
- request:
    method: patch
    uri: https://app.wercker.com/api/v3/applications/StupidCodeFactory/wercker_api
    body:
      encoding: UTF-8
      string: '{"ignoredBranches":["a-dummy-branch"]}'
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
      Content-Type:
      - application/json
      Authorization:
      - Bearer some_api_token
  response:
    status:
      code: 200
      message: OK
    headers:
      Cache-Control:
      - private, no-cache, no-store, must-revalidate
      Content-Type:
      - application/json; charset=utf-8
      Date:
      - Mon, 03 Jul 2017 20:29:42 GMT
      Etag:
      - W/"356-b7d7dd35"
      Server:
      - nginx
      Set-Cookie:
      - express.sid=s%3A-Ygr0OGEjuQ0Ea2c58DxsjIU8KR6rOS9.D8x%2FyqA6XusbuNB8CgyaRobq1gmMYwFScZj2%2FI23LEo;
        Path=/; Expires=Mon, 17 Jul 2017 20:29:42 GMT; HttpOnly; Secure
      Strict-Transport-Security:
      - max-age=10886400; includeSubDomains; preload
      X-Content-Type-Options:
      - nosniff
      X-Frame-Options:
      - DENY
      X-Powered-By:
      - Express
      Transfer-Encoding:
      - chunked
      Connection:
      - keep-alive
    body:
      encoding: ASCII-8BIT
      string: '{"id":"595a6b1ba01812010072fc1c","url":"https://app.wercker.com/api/v3/applications/stupidcodefactory/wercker_api","name":"wercker_api","owner":{"type":"wercker","name":"yann","avatar":{"gravatar":"a4346267407e112504b5dab1dac534ea"},"userId":"56a4de11212b43b24e0b6175","meta":{"username":"StupidCodeFactory","type":"user","werckerEmployee":false}},"builds":"https://app.wercker.com/api/v3/applications/stupidcodefactory/wercker_api/builds","deploys":"https://app.wercker.com/api/v3/applications/stupidcodefactory/wercker_api/deploys","scm":{"type":"git","owner":"StupidCodeFactory","domain":"github.com","repository":"wercker_api"},"badgeKey":"15fd697b0b3ff854e408a5c256e6737b","createdAt":"2017-07-03T16:04:43.374Z","updatedAt":"2017-07-03T20:29:42.731Z","theme":"Amethyst","settings":{"privacy":"public","stack":6,"ignoredBranches":["a-dummy-branch"]}}'
    http_version: 
  recorded_at: Mon, 03 Jul 2017 20:29:42 GMT
- request:
    method: get
    uri: https://app.wercker.com/api/v3/applications/StupidCodeFactory/wercker_api
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
      Authorization:
      - Bearer some_api_token
  response:
    status:
      code: 200
      message: OK
    headers:
      Cache-Control:
      - private, no-cache, no-store, must-revalidate
      Content-Type:
      - application/json; charset=utf-8
      Date:
      - Mon, 03 Jul 2017 20:29:43 GMT
      Etag:
      - W/"6EhHuDHWd41hW32Z7TW/qQ=="
      Server:
      - nginx
      Set-Cookie:
      - express.sid=s%3A0N9C2dgJdcnmfwPmzEn2TB9_OlaqLUuY.180aoY5R7ZOVQEn6frmmpXxbXiGTGg0LNHN7O7o2Oas;
        Path=/; Expires=Mon, 17 Jul 2017 20:29:43 GMT; HttpOnly; Secure
      Strict-Transport-Security:
      - max-age=10886400; includeSubDomains; preload
      X-Content-Type-Options:
      - nosniff
      X-Frame-Options:
      - DENY
      X-Powered-By:
      - Express
      Transfer-Encoding:
      - chunked
      Connection:
      - keep-alive
    body:
      encoding: ASCII-8BIT
      string: '{"id":"595a6b1ba01812010072fc1c","url":"https://app.wercker.com/api/v3/applications/stupidcodefactory/wercker_api","name":"wercker_api","owner":{"type":"wercker","name":"yann","avatar":{"gravatar":"a4346267407e112504b5dab1dac534ea"},"userId":"56a4de11212b43b24e0b6175","meta":{"username":"StupidCodeFactory","type":"user","werckerEmployee":false}},"builds":"https://app.wercker.com/api/v3/applications/stupidcodefactory/wercker_api/builds","deploys":"https://app.wercker.com/api/v3/applications/stupidcodefactory/wercker_api/deploys","scm":{"type":"git","owner":"StupidCodeFactory","domain":"github.com","repository":"wercker_api"},"badgeKey":"15fd697b0b3ff854e408a5c256e6737b","createdAt":"2017-07-03T16:04:43.374Z","updatedAt":"2017-07-03T20:29:42.731Z","allowedActions":["delete_project","update_project","transfer_ownership_project","update_checkout_key","migrate_application","list_authorizations","create_authorization","read_authorization","update_authorization","delete_authorization","read_heroku_collaborators","send_invites","create_key","delete_key","update_key","update_teams","delete_team","update_org","create_member","delete_member","update_member","create_team_members","delete_team_members","org_create_app","org_transferownership_app","org_transfer_apiUser_app","update_project_button","cancel_customer","create_customer","get_customer","update_customer","get_billing","update_billing","update_extended_permissions","get_invoice","list_invoices","list_orginvitations","create_orginvitation","get_orginvitation","delete_orginvitation","resend_orginvitation","deploy_build","reset_deploy_warnings","create_deploytarget","create_target","update_target","delete_target","create_target_trigger","update_target_trigger","read_target_trigger","delete_target_trigger","read_deploytarget","abort_deploy","update_deploytarget","delete_deploytarget","read_deploytargetsettings","application_envcollection","list_key","read_key","create_env_var","update_env_var","delete_env_var","build_project","rebuild_build","abort_build","read_deploy","list_deploysteps","read_deploystep","read_deploytarget_logs","add_pullrequest","receive_push","autodeploy_build","fix_webhook","clear_cache_project","list_teams","list_members","org_read_wallItem","read_docker_image","create_run","abort_run","list_extended_permissions","read_env_var","read_project","list_builds","read_build","list_runs","read_run","list_runsteps","read_runstep","list_buildsteps","read_buildstep","follow_project","unfollow_project","list_targets","read_target","list_workflows","list_collaborators","list_comment","create_comment"],"theme":"Amethyst","settings":{"privacy":"public","stack":6,"ignoredBranches":["a-dummy-branch"]}}'
    http_version: 
  recorded_at: Mon, 03 Jul 2017 20:29:43 GMT
recorded_with: VCR 3.0.3
