require "virtus"
require "wercker_api/version"
require "wercker_api/api_collection"
require "wercker_api/scm"
require "wercker_api/owner"
require "wercker_api/pipeline"
require "wercker_api/run_collection"
require "wercker_api/run"
require "wercker_api/application"
require "wercker_api/application_collection"
require "wercker_api/application/build"
require "wercker_api/application/build_collection"
require "wercker_api/application/deploy"
require "wercker_api/application/deploy_collection"
require "wercker_api/application/workflow"
require "wercker_api/application/workflow_collection"
require "wercker_api/client"

module WerckerAPI; end
